[package]
name = "iced_aksel_tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
iced.workspace = true
iced_core.workspace = true
iced_test.workspace = true
iced_aksel = { path = "../iced_aksel" }

[lib]
name = "common"
path = "common/mod.rs"

[[test]]
name = "core_axes_tests"
path = "core_axes_tests.rs"
harness = true
